# This is a basic workflow to help you get started with Actions

name: Weekly Stats

# Controls when the action will run. 
on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme:
  # This workflow contains a single job called "build"
    name: Update Readme with Metrics
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      - uses: Adhithia/Adhithia@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
